# Generated by Django 5.2.7 on 2025-10-29 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokedex', '0002_trainer_alter_pokemon_height_alter_pokemon_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemon',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='pokemons/'),
        ),
    ]
