# Generated by Django 5.2.7 on 2025-11-07 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokedex', '0005_alter_pokemon_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemon',
            name='type',
            field=models.CharField(choices=[('Fuego', '🔥 Fuego'), ('Agua', '💧 Agua'), ('Planta', '🌿 Planta'), ('Eléctrico', '⚡ Eléctrico'), ('Roca', '🪨 Roca'), ('Tierra', '🌎 Tierra'), ('Volador', '🌬️ Volador'), ('Veneno', '☠️ Veneno'), ('Hielo', '❄️ Hielo'), ('Lucha', '🥋 Lucha'), ('Fantasma', '👻 Fantasma'), ('Psíquico', '🔮 Psíquico'), ('Dragón', '🐉 Dragón'), ('Bicho', '🐛 Bicho'), ('Acero', '⚙️ Acero'), ('Normal', '⚪ Normal'), ('Siniestro', '🌑 Siniestro'), ('Hada', '✨ Hada')], max_length=30),
        ),
    ]
