# Generated by Django 5.2.7 on 2025-11-07 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokedex', '0006_alter_pokemon_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemon',
            name='type',
            field=models.CharField(choices=[('Fuego', '🔥 Fuego'), ('Agua', '💧 Agua'), ('Planta', '🌿 Planta'), ('Eléctrico', '⚡ Eléctrico'), ('Normal', '⚪ Normal')], max_length=30),
        ),
    ]
