# Generated by Django 5.2.7 on 2025-12-03 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pokedex', '0008_trainer_photo_alter_pokemon_trainer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trainer',
            old_name='photo',
            new_name='picture',
        ),
    ]
